#!/bin/bash

#SBATCH -J visualbraking
#SBATCH -p general
#SBATCH -o outputcheckpoint_%j.txt
#SBATCH -e errorcheckpoint_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bdahlber@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4G
#SBATCH --time=4:00:00

echo $A
export PATH="/N/u/bdahlber/Carbonate/Desktop/bin:$PATH"
source "/N/u/bdahlber/Carbonate/Env1/bin/activate"
python3 "/N/u/bdahlber/Carbonate/Desktop/run_carbonate.py" $A
